const playerProfile = [
	{
		id: 1,
		position: "keeper",
		player: [
			{
				id: 1,
				name: "Edouard Mendy",
				age: 30,
				height: 170,
				weight: 80,
				birthday: "October 2, 2022",
				position: "Goal Keeper",
				nationality: "Senegal",
				matches: 5,
				goals: 1,
				jersey: 7,
				image: require("../assets/Players/mendy.jpeg"),
				countryFlag: require("../assets/Flags/br.png"),
			},
			{
				id: 2,
				name: "Kepa Arrizabalaga",
				age: 28,
				height: 170,
				weight: 80,
				birthday: "October 2, 2022",
				position: "Goal Keeper",
				nationality: "Spain",
				matches: 13,
				goals: 0,
				jersey: 7,
				image: require("../assets/Players/kepa.jpeg"),
				countryFlag: require("../assets/Flags/br.png"),
			},
			{
				id: 3,
				name: "Marcus Bettinelli",
				age: 30,
				height: 170,
				weight: 80,
				birthday: "October 2, 2022",
				position: "Goal Keeper",
				nationality: "England",
				matches: 14,
				goals: 0,
				jersey: 7,
				image: require("../assets/Players/marcus.jpeg"),
				countryFlag: require("../assets/Flags/br.png"),
			},
		],
	},
	{
		id: 2,
		position: "defender",
		player: [
			{
				id: 1,
				name: "Trevoh Chalobah",
				age: 23,
				height: 190,
				weight: 80,
				birthday: "July 23, 1999",
				position: "Defender",
				nationality: "England",
				matches: 27,
				goals: 3,
				jersey: 2,
				image: require("../assets/Players/chab.jpeg"),
				countryFlag: require("../assets/Flags/en.png"),
			},
			{
				id: 2,
				name: "Kalidou Koulibaly",
				age: 31,
				height: 187,
				weight: 80,
				birthday: "June 20, 1991",
				position: "Defender",
				nationality: "Senegal",
				matches: 8,
				goals: 1,
				jersey: 26,
				image: require("../assets/Players/kolibaly.jpeg"),
				countryFlag: require("../assets/Flags/sn.png"),
			},
			{
				id: 3,
				name: "César Azpilicueta",
				age: 33,
				height: 178,
				weight: 80,
				birthday: "August 28, 1989",
				position: "Defender",
				nationality: "Spain",
				matches: 334,
				goals: 10,
				jersey: 28,
				image: require("../assets/Players/cesar.jpeg"),
				countryFlag: require("../assets/Flags/es.png"),
			},
			{
				id: 4,
				name: "Thiago Silva",
				age: 38,
				height: 183,
				weight: 80,
				birthday: "September 22, 1984",
				position: "Defender",
				nationality: "Brasil",
				matches: 66,
				goals: 5,
				jersey: 6,
				image: require("../assets/Players/silva.jpeg"),
				countryFlag: require("../assets/Flags/br.png"),
			},
			{
				id: 5,
				name: "Marc Cucurella",
				age: 24,
				height: 172,
				weight: 80,
				birthday: "July 22, 1998",
				position: "Defender",
				nationality: "Spain",
				matches: 47,
				goals: 1,
				jersey: 7,
				image: require("../assets/Players/marc.jpeg"),
				countryFlag: require("../assets/Flags/es.png"),
			},
			{
				id: 6,
				name: "Wesley Fofana",
				age: 21,
				height: 190,
				weight: 80,
				birthday: "December 17, 2000",
				position: "Defender",
				nationality: "Spain",
				matches: 39,
				goals: 0,
				jersey: 33,
				image: require("../assets/Players/wesley.jpeg"),
				countryFlag: require("../assets/Flags/fr.png"),
			},
		],
	},
	{
		id: 3,
		position: "midfielder",
		player: [
			{
				id: 1,
				name: "Ngolo Kante",
				age: 31,
				height: 170,
				weight: 80,
				birthday: "May 29, 1991",
				position: "Midfilder",
				nationality: "France",
				matches: 304,
				goals: 15,
				jersey: 7,
				image: require("../assets/Players/kante.jpeg"),
				countryFlag: require("../assets/Flags/fr.png"),
			},
			{
				id: 2,
				name: "Reece James",
				age: 22,
				height: 182,
				weight: 80,
				birthday: "Dec 8, 1999",
				position: "Midfilder",
				nationality: "England",
				matches: 196,
				goals: 16,
				jersey: 24,
				image: require("../assets/Players/james.jpeg"),
				countryFlag: require("../assets/Flags/en.png"),
			},
			{
				id: 3,
				name: "Ben Chilwell",
				age: 25,
				height: 178,
				weight: 80,
				birthday: "December 21, 1996",
				position: "Midfilder",
				nationality: "England",
				matches: 142,
				goals: 11,
				jersey: 7,
				image: require("../assets/Players/ben.png"),
				countryFlag: require("../assets/Flags/en.png"),
			},
			{
				id: 4,
				name: "Ruben Loftus-Cheek",
				age: 26,
				height: 191,
				weight: 80,
				birthday: "January 23, 1996",
				position: "Midfilder",
				nationality: "England",
				matches: 145,
				goals: 10,
				jersey: 7,
				image: require("../assets/Players/cheek.jpeg"),
				countryFlag: require("../assets/Flags/en.png"),
			},
			{
				id: 5,
				name: "Jorgino",
				age: 30,
				height: 170,
				weight: 80,
				birthday: "December 12, 1991",
				position: "Midfilder",
				nationality: "England",
				matches: 137,
				goals: 21,
				jersey: 7,
				image: require("../assets/Players/jorgino.jpeg"),
				countryFlag: require("../assets/Flags/it.png"),
			},
		],
	},
	{
		id: 4,
		position: "forward",
		player: [
			{
				id: 1,
				name: "Mason Mount",
				age: 26,
				height: 178,
				weight: 80,
				birthday: "October 1, 1999",
				position: "Forward",
				nationality: "England",
				matches: 118,
				goals: 26,
				jersey: 19,
				image: require("../assets/Players/mount.jpeg"),
				countryFlag: require("../assets/Flags/en.png"),
			},
			{
				id: 2,
				name: "Jorgino",
				age: 30,
				height: 170,
				weight: 80,
				birthday: "October 2, 2022",
				position: "Goal Keeper",
				nationality: "Italy",
				matches: 7,
				goals: 5,
				jersey: 5,
				image: require("../assets/Players/jorgino.jpeg"),
				countryFlag: require("../assets/Flags/br.png"),
			},
			{
				id: 3,
				name: "Kai Havertz",
				age: 23,
				height: 118,
				weight: 68,
				birthday: "June 11, 1999",
				position: "Forward",
				nationality: "Germany",
				matches: 8,
				goals: 15,
				jersey: 29,
				image: require("../assets/Players/kai.jpeg"),
				countryFlag: require("../assets/Flags/de.png"),
			},
			{
				id: 4,
				name: "Pierre-Emerick Aubameyang",
				age: 33,
				height: 187,
				weight: 80,
				birthday: "June 18, 1989",
				position: "Forward",
				nationality: "Gabon",
				matches: 134,
				goals: 69,
				jersey: 9,
				image: require("../assets/Players/Aubameyang.jpeg"),
				countryFlag: require("../assets/Flags/ga.png"),
			},
			{
				id: 5,
				name: "Raheem Sterling",
				age: 27,
				height: 170,
				weight: 80,
				birthday: "December 8, 1994",
				position: "Forward",
				nationality: "England",
				matches: 332,
				goals: 112,
				jersey: 17,
				image: require("../assets/Players/sterling.jpeg"),
				countryFlag: require("../assets/Flags/en.png"),
			},
			{
				id: 6,
				name: "Armando Broja",
				age: 21,
				height: 191,
				weight: 80,
				birthday: "December 8, 1994",
				position: "Forward",
				nationality: "Albania",
				matches: 44,
				goals: 7,
				jersey: 18,
				image: require("../assets/Players/broja.jpeg"),
				countryFlag: require("../assets/Flags/es.png"),
			},
		],
	},
];

export default playerProfile;
